security:
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 12
    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'email'
    firewalls:
        main:
            anonymous: true
            lazy: true
            provider: users
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
